apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: ghcr.io/fpommerening/container-training.webapp:2.0.0
        name: app